Kubernetes monitoring
otus-kuber-2019-12/EvgeniiMikhailov_platform pull request #8
Opened 2020-02-25 07:16 UTC by EvgeniiMikhailov

# Выполнено ДЗ №

 - [x] Основное ДЗ

## В процессе сделано:
 - Установлен prometheus-operator с помощью helm3
 - Создан образ Nginx который отдает метрики на порту 8080 по пути /stub_status
 - Prometheus настроен на сбор метрик nginx c помощью Nginx exporter 

## Как запустить проект и проверить работоспособность описано в README.md в папке kubernetes-monitoring:
 - Например, запустить команду X в директории Y

## PR checklist:
 - [x] Выставлен label с номером домашнего задания

2020-03-06 10:18 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. К сожалению закралась небольшая ошибочка, подробности в комментарии к деплойменту. Возвращаю на доработку.

2020-03-06 10:18 UTC, mrgreyves commented on kubernetes-monitoring/deployment.yaml
> +      - image: nginx/nginx-prometheus-exporter:0.6.0
Закралась небольшая ошибочка. Экспортеру нужно указать где ему брать значения.

2020-03-06 18:00 UTC, EvgeniiMikhailov commented on kubernetes-monitoring/deployment.yaml
> +      - image: nginx/nginx-prometheus-exporter:0.6.0
Экспортеру не всегда обязательно указывать откуда брать значения. Я в образе nginx отдаю статистику по стандартному порту (8080) и стандартному пути (/stub_status) Конфиг для nginx https://raw.githubusercontent.com/otus-kuber-2019-12/EvgeniiMikhailov_platform/kubernetes-monitoring/kubernetes-monitoring/nginx-with-basic-status/status.conf в этом случае не нужно указывать допалнительный параметр args: ['-nginx.scrape-uri', 'http://localhost/basic_status']. Мне кажется такой вариант логичнее так как:
1. Создан отдельный конфиг для nginx, который не будет мешать разработчикам.
2. Статистика отдается стандартным способом.

2020-03-09 21:00 UTC, mrgreyves commented on kubernetes-monitoring/deployment.yaml
> +      - image: nginx/nginx-prometheus-exporter:0.6.0
Да, все верно. Май бед =)

2020-03-09 21:01 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-03-13 09:32 UTC, merged